### ISSUE TITLE
normal config

### ISSUE THREAD

**Issue by GogUwU** [RedPxnda/RespawnObelisks#1]
make config save in .minecraft/config not in .minecraft/saves/(name of the world)/server config

**Comment by RedPxnda** [comment]
Forge has a config system that allows for quite a bit of variation. Server configs (which I’m currently using) only apply from the server. This allows for server admins to modify their configs without the players needing to make the same change. 

If you want to have the config apply to all worlds, put your modified config in the “defaultconfigs”(might be different, but it’s roughly the same name) folder. 

In the next update, this has been changed due to a variety of factors(mod will be multi loader so I can’t use forge’s system, and I’m using a config library that doesn’t make this differentiation), so when that update drops the config will work how you imagine.
