### ISSUE TITLE
[BUG] Player Cannot Respawn With 'Home Bed Only' Config Option from Sleep Tight

### ISSUE THREAD

**Issue by CraftyZombie** [RedPxnda/RespawnObelisks#12]
**Describe the bug**
Sleep Tight introduced a new config option which only allows you to respawn in beds after sleeping in them for a certain number of nights. When that's enabled, along with bed respawning in this mod, the player cannot respawn.

**To Reproduce**

1. Enable bed respawning in Respawn Obelisks.
2. Set only_respawn_in_home_bed = true in Sleep Tight's common config.
3. Set your spawn point at a bed "you can set the number of nights to make it a home bed using commands.
4. Use /kill.
5. Try to respawn.

**Expected behavior**
I expected to respawn into the world.

**Screenshots**
![2024-01-13_20 00 30](https://github.com/RedPxnda/RespawnObelisks/assets/70306455/493d5b68-2dc0-4417-a525-9527282a207e)

**Versions**
Architectury 9.1.12
Resourceful Config 2.1.2
Respawn Obelisks 2.4-d
Sleep Tight 1.20-1.1.14
Moonlight Library 1.20-2.8.82

Forge Version: 47.2.19
Minecraft Version: 1.20.1

**Additional notes**
[latest.log](https://github.com/RedPxnda/RespawnObelisks/files/13930263/latest.log)
[debug.log](https://github.com/RedPxnda/RespawnObelisks/files/13930264/debug.log)
(There is no crash report, it does not crash the game. In fact, the internal server is still running.)

**Comment by RedPxnda** [comment]
Respawn Obelisks intentionally tries to disallow bed respawning. Can you show me your respawn obelisks config?

**Comment by CraftyZombie** [comment]
[respawnobelisks.jsonc](https://github.com/RedPxnda/RespawnObelisks/files/13930320/respawnobelisks.jsonc)
Sure thing.

**Comment by RedPxnda** [comment]
Unfortunately my phone can't seem to open jsonc files. Please could you send it in a paste, for example hastebin?
Sorry for the inconvenience.

**Comment by CraftyZombie** [comment]
Totally fine.
https://hastebin.com/share/oqurofezap.kotlin

**Comment by RedPxnda** [comment]
Huh, you do have it setup correctly. I'll take a look into this tomorrow. Thanks for letting me know.

**Comment by CraftyZombie** [comment]
Of course. Much appreciated.

Also to be clear normally bed respawning works fine with both mods installed, the glitch only happens when that aforementioned config option is enabled.

**Comment by RedPxnda** [comment]
Unfortunately, you will probably have to report this to the creator of Sleep Tight, despite what the log says. 
When you create that issue, I can provide some additional context, but if you want that here:

I'm not entirely sure how Forge's Capabilities system works, since I've always used my own solutions in place of it, but it is possible that the Player, being a CapabilityProvider, does not have valid capabilities when in the respawn screen, meaning CapabilityProvider#valid is false. When that is false, Player#getCapability will always return null(or rather, an empty optional):
![when dead, valid is false on the player](https://github.com/RedPxnda/RespawnObelisks/assets/54185270/195d1f6a-cf74-48e5-a370-cea0dec64ab5)
![valid being false means getCapability returns an empty optional](https://github.com/RedPxnda/RespawnObelisks/assets/54185270/b206f3c4-1316-4d14-af89-477880554c62)

**Comment by RedPxnda** [comment]
In fact, this happens without Respawn Obelisks installed.
