### ISSUE TITLE
[BUG] When spawn point is set at an end obelisk you can't exit the end

### ISSUE THREAD

**Issue by UnnaturalTwilight** [RedPxnda/RespawnObelisks#6]
**Describe the bug**
When spawn point is set an end obelisk going through the end exit portal returns you to your obelisk in the end preventing you from returning to the overworld without removing the core of you obelisk.
 
**To Reproduce**
Activate an obelisk in the end
go into the exit portal

**Expected behaviour**
Returned to the overworld ether at your last overworld obelisk or world spawn

**Versions**
 - Minecraft Version: 1.19.2
 - Respawn Obelisk Version: 2.1b
 - Fabric Loader Version: 0.14.22
 - Fabric API Version: 0.76.1

**Additional notes**
Hopefully this can get fixed as i would like to be able to respawn at an end base while still having access to the overworld.

**Comment by RedPxnda** [comment]
I can't say this is necessarily a bug. Going through the end portal just sends you to your spawn, and respawn obelisks just set your spawn. 
I can add a config option to make going through the end portal while having an end obelisk set send you to world spawn, but adding additional tracking specifically for your last explicitly overworld obelisk is not something I really want to do, since right now I just use vanilla's respawn system.
At some point I do plan on adding some features for a sort of "shadowed" respawn point so that respawn obelisks can act as more of an addition rather than just a replacement for bed respawning, perhaps this could tack in there? (Specifically, (would disabled by default) you can store another respawn point that has lower priority than your actual, and with some other config options you'll be able to control when this additional respawn point could be used.)

**Comment by UnnaturalTwilight** [comment]
I understand what you are saying and this is mostly just an inconvenience in a very specific use cans so i wouldn't expect a lot of work put into it, but even just a config option to be sent to world spawn would be amazing to have. 
if it is too much work don't worry about it as i can use another mod to get back to the overworld.

**Comment by RedPxnda** [comment]
It's truly not too much work, it's just that in the current update I'm working on I have quite a few features that are incomplete and uncommitted, since they're not stable yet. I want to release these features in the next update, which means any other simpler features (like this) will be held back for a bit.

But I'll try to add this for the next update.

**Comment by SigmaFlame** [comment]
You should makes that using the end portal leads to the overworld default spawn location if the spawn point of the player is inside the end.
Another solution would be to completely remove the ability to set a respawn point in the end.

**Comment by RedPxnda** [comment]
Fixed as of 2.5. Added config option to control how going through an end portal takes you to your spawn point. By default, it will take you to world spawn if your spawn point is set in the end.
